version: 1.0.{build}
image: Visual Studio 2017
install:
- cmd: >-
    cd %APPVEYOR_BUILD_FOLDER%

    git submodule update --init --recursive

    nuget restore OpenBullet.sln

build:
  verbosity: normal
after_build:
- cmd: 7z a SilverBullet.zip %APPVEYOR_BUILD_FOLDER%\SilverBullet\bin\debug\
artifacts:
- path: SilverBullet.zip
  name: SilverBullet
